### ISSUE TITLE
Unable to Create MG group

### ISSUE THREAD

**Issue by ArthiSaravana** [tw3lveparsecs/azure-bicep-management-groups#2]
I tried to create management group but am getting an error. help me with this

targetScope = 'managementGroup'

@description('Management group id')
param managementGroupId string

@description('Management group display name')
param managementGroupDisplayName string

@description('Management group id of the parent management group')
param parentManagementGroupId string = 'main-root

resource managementGroup 'Microsoft.Management/managementGroups@2020-05-01' = {
  name: managementGroupId
  scope: tenant()
  properties: {
    displayName: managementGroupDisplayName
    details: {
      parent: {
        id: parentManagementGroupId
      }
    }
  }
}

Error:
{"code": "AuthorizationFailed", "message": "The client xxxx.com with object id 'fd920e35-41d9-4fcc-8546-9793d2369ede' does not have authorization to perform action 'Microsoft.Resources/deployments/validate/action' over scope '/providers/Microsoft.Resources/deployments/mgg1' or the scope is invalid. If access was recently granted, please refresh your credentials."}

**Comment by tw3lveparsecs** [comment]
looks like the account you are using to deploy doesnt have the correct access and the targetscope should be set to tenant not mg. 

Have a look at the deployment examples and ensure target scope is set to tenant and you have the following permissions set to run tenant level deployments: https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-to-tenant?tabs=azure-cli#required-access

**Comment by ArthiSaravana** [comment]
I tried setting tenant as well. but same error. I have contributor access but am unable to deploy

**Comment by ArthiSaravana** [comment]
close
